AllCops:
  TargetRubyVersion: 2.2

require:
  - rubocop-rspec

# Offense count: 1
Metrics/AbcSize:
  Max: 21

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 45

# Offense count: 1
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 11

# Offense count: 3
# Configuration parameters: AggregateFailuresByDefault.
RSpec/MultipleExpectations:
  Max: 3

# Offense count: 2
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'lib/sequel_vault.rb'

# Offense count: 4
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 113
