Style/AlignHash:
  Enabled: false

Style/AlignArray:
  Enabled: false

Style/AlignParameters:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/IndentHash:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/MultilineOperationIndentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/LineLength:
  Max: 250

Metrics/MethodLength:
  Max: 250

Metrics/ClassLength:
  Max: 250

Lint/UselessAssignment:
  Enabled: false
